---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: nginx-demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-prod # 自动申请证书
spec:
  ingressClassName: higress
  tls:
    - hosts:
        - nginx.awssre.com
      secretName: nginx-awssre-com-tls
  rules:
    - host: nginx.awssre.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80